# yaml-language-server: $schema=https://taskfile.dev/schema.json

#####################################################################
# Docs: https://taskfile.dev                                        #
#                                                                   #
# Use npx with the "--no" argument to ensure that dependencies with #
# versions different from those in package.json are not downloaded. #
#####################################################################

version: "3"

tasks:
  default:
    desc: List all available commands
    cmd: task --list-all

  ci:
    desc: Run full CI pipeline (format, lint, test, build)
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  dev:
    desc: Start development server
    cmd: veta dev

  build:
    desc: Build the project locally
    cmds:
      - task: build:js
      - veta build

  build:js:
    desc: Build javascript of the project
    cmds:
      - rm -rf ./public/_vara/js/build
      - npx --no esbuild ./public/_vara/js/src/head/index.js --bundle --minify --outfile=./public/_vara/js/build/head.js
      - npx --no esbuild ./public/_vara/js/src/docs/index.js --bundle --minify --outfile=./public/_vara/js/build/docs.js

  format:
    desc: Run formatters
    cmd: dprint fmt --config ./dprint.json --log-level warn

  lint:
    desc: Run linters
    cmd: dprint check --config ./dprint.json --log-level warn

  test:
    desc: Run tests
    cmd: node --test filters/*.test.js functions/*.test.js
